import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Akkadian to English Neural Machine Translation\n",
                "### Deep Past Initiative Challenge\n",
                "\n",
                "This notebook implements a GRU-based Language Model for translating Old Assyrian (Akkadian) transliterations into English. It includes data preprocessing, model definition, training, and submission generation."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import re\n",
                "import sys\n",
                "import math\n",
                "import time\n",
                "import pickle\n",
                "import random\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.nn.functional as F\n",
                "import nltk\n",
                "from nltk.tokenize import word_tokenize\n",
                "\n",
                "nltk.download('punkt', quiet=True)\n",
                "nltk.download('punkt_tab', quiet=True)\n",
                "\n",
                "# Device configuration\n",
                "device = torch.device(\"cuda:0\" if torch.cuda.is_available() else \"cpu\")\n",
                "print(f\"Using device: {device}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Data Preprocessing\n",
                "Cleaning the transliterated Akkadian text by removing modern scribal notations and handling gaps/breaks."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def preprocess_transliteration(text):\n",
                "    if not isinstance(text, str):\n",
                "        return \"\"\n",
                "    \n",
                "    # 1. Remove modern scribal notations\n",
                "    text = re.sub(r'[!?/:\\.\\(\\)\u02fd\u02fe]', '', text)\n",
                "    text = text.replace('<', '').replace('>', '')\n",
                "    text = text.replace('[', '').replace(']', '')\n",
                "    \n",
                "    # 2. Replace breaks, gaps, superscripts, subscripts\n",
                "    text = text.replace('x', '<gap>')\n",
                "    text = text.replace('...', '<big_gap>')\n",
                "    \n",
                "    # 3. Specific character substitutions (H-substitutions)\n",
                "    text = text.replace('\u1e2b', 'h').replace('\u1e2a', 'H')\n",
                "    \n",
                "    # Normalize spaces\n",
                "    text = re.sub(r'\\s+', ' ', text).strip()\n",
                "    return text\n",
                "\n",
                "def preprocess_translation(text):\n",
                "    if not isinstance(text, str):\n",
                "        return \"\"\n",
                "    text = text.replace('\\n', ' ')\n",
                "    text = re.sub(r'\\s+', ' ', text).strip()\n",
                "    return text"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Utilities and Data Preparation\n",
                "Functions for loading the corpus, creating a dictionary, and preparing padded batches."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class ProgressBar:\n",
                "    def __init__(self, bar_width=50):\n",
                "        self.bar_width = bar_width\n",
                "        self.period = None\n",
                "        self.item = 0\n",
                "    def start(self, count):\n",
                "        self.item = 0\n",
                "        self.period = max(1, int(count / self.bar_width))\n",
                "        sys.stdout.write(\"[\" + (\" \" * self.bar_width) + \"]\")\n",
                "        sys.stdout.flush()\n",
                "        sys.stdout.write(\"\\b\" * (self.bar_width + 1))\n",
                "    def tick(self):\n",
                "        if self.item > 0 and self.item % self.period == 0:\n",
                "            sys.stdout.write(\"-\")\n",
                "            sys.stdout.flush()\n",
                "        self.item += 1\n",
                "    def stop(self):\n",
                "        sys.stdout.write(\"]\\n\")\n",
                "\n",
                "def get_dictionary(corpus, special_tokens, threshold=2):\n",
                "    dictionary = {}\n",
                "    for s in corpus:\n",
                "        for w in s:\n",
                "            dictionary[w] = dictionary.get(w, 0) + 1\n",
                "    words = special_tokens + [w for w in sorted(dictionary) if dictionary[w] > threshold]\n",
                "    return {w: i for i, w in enumerate(words)}\n",
                "\n",
                "def prepare_data(train_csv_path, start_token, end_token, unk_token, pad_token, trans_token):\n",
                "    df = pd.read_csv(train_csv_path)\n",
                "    \n",
                "    source_corpus = [word_tokenize(preprocess_transliteration(row['transliteration'])) for _, row in df.iterrows()]\n",
                "    target_corpus = [word_tokenize(preprocess_translation(row['translation'])) for _, row in df.iterrows()]\n",
                "    \n",
                "    all_tokens = source_corpus + target_corpus\n",
                "    special_tokens = [start_token, end_token, unk_token, pad_token, trans_token]\n",
                "    word2ind = get_dictionary(all_tokens, special_tokens)\n",
                "    \n",
                "    unk_idx = word2ind[unk_token]\n",
                "    corpus = [[start_token] + s + [trans_token] + t + [end_token] for s, t in zip(source_corpus, target_corpus)]\n",
                "    corpus_indices = [[word2ind.get(w, unk_idx) for w in s] for s in corpus]\n",
                "    \n",
                "    # Split train/dev\n",
                "    random.seed(42)\n",
                "    indices = list(range(len(corpus_indices)))\n",
                "    random.shuffle(indices)\n",
                "    corpus_indices = [corpus_indices[i] for i in indices]\n",
                "    \n",
                "    split_idx = int(0.9 * len(corpus_indices))\n",
                "    return corpus_indices[:split_idx], corpus_indices[split_idx:], word2ind"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Model Architecture\n",
                "A GRU-based Language Model that learns to predict the next token in the sequence `<S> Source <TRANS> Target </S>`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class LanguageModel(nn.Module):\n",
                "    def __init__(self, vocab_size, emb_dim, hidden_dim, num_layers, start_idx, end_idx, pad_idx, trans_idx):\n",
                "        super().__init__()\n",
                "        self.vocab_size = vocab_size\n",
                "        self.emb = nn.Embedding(vocab_size, emb_dim, padding_idx=pad_idx)\n",
                "        self.rnn = nn.GRU(emb_dim, hidden_dim, num_layers=num_layers, batch_first=True)\n",
                "        self.proj = nn.Linear(hidden_dim, vocab_size)\n",
                "        self.start_idx = start_idx\n",
                "        self.end_idx = end_idx\n",
                "        self.pad_idx = pad_idx\n",
                "        self.trans_idx = trans_idx\n",
                "\n",
                "    def prepare_padded_batch(self, source):\n",
                "        m = max(len(s) for s in source)\n",
                "        sents_padded = [s + (m - len(s)) * [self.pad_idx] for s in source]\n",
                "        return torch.tensor(sents_padded, dtype=torch.long, device=device)\n",
                "\n",
                "    def forward(self, source):\n",
                "        x = self.prepare_padded_batch(source)\n",
                "        B, T = x.shape\n",
                "        inp = x[:, :-1]\n",
                "        tgt = x[:, 1:]\n",
                "        mask = (tgt != self.pad_idx)\n",
                "        \n",
                "        emb = self.emb(inp)\n",
                "        h, _ = self.rnn(emb)\n",
                "        logits = self.proj(h)\n",
                "        log_probs = F.log_softmax(logits, dim=-1)\n",
                "        \n",
                "        tgt_flat = tgt.reshape(-1)\n",
                "        lp_flat = log_probs.reshape(-1, self.vocab_size)\n",
                "        token_lp = lp_flat[torch.arange(tgt_flat.numel(), device=device), tgt_flat]\n",
                "        token_lp = token_lp.view(B, T - 1)\n",
                "        \n",
                "        valid_counts = mask.sum().clamp(min=1)\n",
                "        return - (token_lp[mask].sum() / valid_counts)\n",
                "\n",
                "    @torch.no_grad()\n",
                "    def generate(self, prefix, limit=200):\n",
                "        seq = list(prefix)\n",
                "        x = torch.tensor([seq], dtype=torch.long, device=device)\n",
                "        emb = self.emb(x)\n",
                "        output, state = self.rnn(emb)\n",
                "        \n",
                "        last_h = output[:, -1:, :]\n",
                "        logits = self.proj(last_h)\n",
                "        cur = torch.argmax(logits.view(-1)).item()\n",
                "        seq.append(cur)\n",
                "        \n",
                "        steps = 1\n",
                "        while steps < limit and cur != self.end_idx:\n",
                "            x_next = torch.tensor([[cur]], dtype=torch.long, device=device)\n",
                "            emb_next = self.emb(x_next)\n",
                "            output, state = self.rnn(emb_next, state)\n",
                "            logits = self.proj(output)\n",
                "            cur = torch.argmax(logits.view(-1)).item()\n",
                "            seq.append(cur)\n",
                "            steps += 1\n",
                "        return seq"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Training\n",
                "Setting hyperparameters and running the training loop."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Hyperparameters\n",
                "START_TOKEN, END_TOKEN, UNK_TOKEN, PAD_TOKEN, TRANS_TOKEN = '<S>', '</S>', '<UNK>', '<PAD>', '<TRANS>'\n",
                "EMB_DIM = 128\n",
                "HIDDEN_DIM = 256\n",
                "NUM_LAYERS = 1\n",
                "LEARNING_RATE = 0.0005\n",
                "BATCH_SIZE = 16\n",
                "CLIP_GRAD = 5.0\n",
                "MAX_EPOCHS = 20\n",
                "\n",
                "train_csv = 'Akkadian to English/deep-past-initiative-machine-translation/train.csv'\n",
                "if not os.path.exists(train_csv):\n",
                "    # Fallback for Kaggle environment if needed\n",
                "    train_csv = '/kaggle/input/deep-past-initiative-machine-translation/train.csv'\n",
                "\n",
                "train_corpus, dev_corpus, word2ind = prepare_data(train_csv, START_TOKEN, END_TOKEN, UNK_TOKEN, PAD_TOKEN, TRANS_TOKEN)\n",
                "\n",
                "nmt = LanguageModel(\n",
                "    vocab_size=len(word2ind), emb_dim=EMB_DIM, hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS,\n",
                "    start_idx=0, end_idx=1, pad_idx=3, trans_idx=4\n",
                ").to(device)\n",
                "\n",
                "optimizer = torch.optim.Adam(nmt.parameters(), lr=LEARNING_RATE)\n",
                "best_perplexity = math.inf\n",
                "\n",
                "def calculate_perplexity(model, data, batch_size):\n",
                "    model.eval()\n",
                "    h_sum, count = 0, 0\n",
                "    for b in range(0, len(data), batch_size):\n",
                "        batch = data[b:min(b + batch_size, len(data))]\n",
                "        l = sum(len(s) - 1 for s in batch)\n",
                "        count += l\n",
                "        with torch.no_grad():\n",
                "            h_sum += l * model(batch).item()\n",
                "    return math.exp(h_sum / count)\n",
                "\n",
                "print(\"Starting training...\")\n",
                "for epoch in range(MAX_EPOCHS):\n",
                "    nmt.train()\n",
                "    idx = np.random.permutation(len(train_corpus))\n",
                "    for b in range(0, len(idx), BATCH_SIZE):\n",
                "        batch = [train_corpus[i] for i in idx[b : b + BATCH_SIZE]]\n",
                "        loss = nmt(batch)\n",
                "        optimizer.zero_grad()\n",
                "        loss.backward()\n",
                "        torch.nn.utils.clip_grad_norm_(nmt.parameters(), CLIP_GRAD)\n",
                "        optimizer.step()\n",
                "    \n",
                "    perp = calculate_perplexity(nmt, dev_corpus, BATCH_SIZE)\n",
                "    print(f\"Epoch {epoch+1}/{MAX_EPOCHS}, Perplexity: {perp:.4f}\")\n",
                "    if perp < best_perplexity:\n",
                "        best_perplexity = perp\n",
                "        torch.save(nmt.state_dict(), 'best_model.pth')\n",
                "\n",
                "if os.path.exists('best_model.pth'):\n",
                "    nmt.load_state_dict(torch.load('best_model.pth'))"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Submission Generation\n",
                "Predicting translations for the test set and saving to `submission.csv`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "test_csv = 'Akkadian to English/deep-past-initiative-machine-translation/test.csv'\n",
                "if not os.path.exists(test_csv):\n",
                "    test_csv = '/kaggle/input/deep-past-initiative-machine-translation/test.csv'\n",
                "\n",
                "test_df = pd.read_csv(test_csv)\n",
                "words = {i: w for w, i in word2ind.items()}\n",
                "unk_idx = word2ind[UNK_TOKEN]\n",
                "trans_idx = word2ind[TRANS_TOKEN]\n",
                "\n",
                "nmt.eval()\n",
                "results = []\n",
                "pb = ProgressBar()\n",
                "pb.start(len(test_df))\n",
                "\n",
                "for _, row in test_df.iterrows():\n",
                "    clean_text = preprocess_transliteration(row['transliteration'])\n",
                "    tokens = word_tokenize(clean_text)\n",
                "    input_indices = [0] + [word2ind.get(w, unk_idx) for w in tokens] + [trans_idx]\n",
                "    \n",
                "    with torch.no_grad():\n",
                "        r = nmt.generate(input_indices)\n",
                "    \n",
                "    try:\n",
                "        st = r.index(trans_idx)\n",
                "        trans_tokens = [words[i] for i in r[st + 1:-1]]\n",
                "        translation = ' '.join(trans_tokens)\n",
                "    except:\n",
                "        translation = \"\"\n",
                "    \n",
                "    results.append({'id': row['id'], 'translation': translation})\n",
                "    pb.tick()\n",
                "pb.stop()\n",
                "\n",
                "submission_df = pd.DataFrame(results)\n",
                "submission_df.to_csv('submission.csv', index=False)\n",
                "print(\"Submission file saved as submission.csv\")\n",
                "submission_df.head()"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.10"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open('Akkadian_NMT_Submission.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)
